#!/bin/bash

#############
## Version ##
#############
# v0.1 - 2021/09/19


# Fonction de vérification d'un fichier MKV
function MKVFileCheck
{
    # $1 : Doit être une url

    local ErrorText

    # Vérifie que le fichier existe
    if [[ ! -f "${1}" ]]
    then
        if [[ "${LANG}" == fr* ]]
        then
            ErrorText="Le fichier <b>${1}</b> n'existe pas !"
        else
            ErrorText="The <b>${1}</b> file doesn't exist!"
        fi

    # Vérifie que le fichier est de type matroska
    elif [[ $(mimetype -b "${1}") != "video/x-matroska" ]]
    then
        if [[ "${LANG}" == fr* ]]
        then
            ErrorText="Le fichier <b>${1}</b> n'est pas un fichier matroska (mkv) !"
        else
            ErrorText="The <b>${1}</b> file isn't a matroska file (mkv)!"
        fi
    fi

    # S'il y a une erreur
    if [[ "${ErrorText}" ]]
    then
        if [[ "${LANG}" == fr* ]]
        then
            ErrorMsg "Titres des MKV" "${ErrorText}"
        else
            ErrorMsg "MKV titles" "${ErrorText}"
        fi

        return 1
    fi

    return 0
}


# Fonction vérifiant les dépendances
function Dependencies
{
    # ${@} : Les arguments doivent être de type : commande:paquet ou commande (si paquet = commande)

    local Dependencie Command Paquet

    # Vérification des dépendances
    for Dependencie in "${@}"
    do
        # Nom de la commande et du paquet Ubuntu associé
        Command="${Dependencie%:*}"
        Paquet="${Dependencie#*:}"

        # Si la commande n'existe pas
        if [[ -z $(which ${Command}) ]]
        then
            if [[ "${LANG}" == fr* ]]
            then
                ErrorMsg "Titres des MKV" "La commande <b>${Command}</b> est introuvable et est nécessaire !<br><br>Pour installer la commande : <b>sudo apt install ${Paquet}</b>"
            else
                ErrorMsg "MKV titles" "The <b>${Command}</b> command cannot be found and is required!<br><br>To install the command: <b>sudo apt install ${Paquet}</b>"
            fi

            return 1
        fi
    done

    return 0
}


# Fonction d'affichage des erreurs
function ErrorMsg
{
    # $1 : Titre à afficher
    # $2 : Message à afficher

    local Message

    if [[ $(which kdialog) ]]
    then
        kdialog \
            --title "${1}" \
            --icon "tag-edit" \
            --error "${2}"
    fi
}




###############################################
## Suppression des fichiers attachés aux MKV ##
###############################################
# Vérification des dépendances
Dependencies mkvpropedit:mkvtoolnix mkvinfo:mkvtoolnix || exit 1

# Traitement des fichiers
for File in "${@}"
do
    # Vérification du fichier MKV
    MKVFileCheck "${File}" || continue

    # Titre actuel
    Title=$(LANG=en mkvinfo "${File}" | sed -n "/+ Title/ s/.*Title: //p")

    # Message demandant le nouveau nom
    if [[ "${LANG}" == fr* ]]
    then
        NewTitle=$(kdialog \
        --title "Nouveau titre" \
        --icon "tag-edit" \
        --inputbox "Indiquer le nouveau titre du fichier MKV :" "${Title}") || continue

    else
        NewTitle=$(kdialog \
        --title "New title" \
        --icon "tag-edit" \
        --inputbox "Set the new title of the MKV file:" "${Title}") || continue
    fi

    # Mise à jour du nouveau titre
    mkvpropedit "${File}" --edit info -s "title=${NewTitle}"
done

# Message de fin de traitement
if [[ "${LANG}" == fr* ]]
then
    kdialog \
    --title "Titres des fichiers MKV" \
    --icon "tag-edit" \
    --dontagain hizo-service-menus.cfg:MKVEditTitle \
    --msgbox "Mise à jour des titres des fichiers MKV terminée."

else
    kdialog \
    --title "Title of the MKV files" \
    --icon "tag-edit" \
    --dontagain hizo-service-menus.cfg:MKVEditTitle \
    --msgbox "Update of the titles of the MKV files completed."
fi
